// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjV9QUunWYzqI1-_Q6HUX0llZr16SXJKA',
    appId: '1:187217290981:web:2069b35447670036d9d60c',
    messagingSenderId: '187217290981',
    projectId: 'storage-3e09b',
    authDomain: 'storage-3e09b.firebaseapp.com',
    storageBucket: 'storage-3e09b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnR5ixlTYvG0GER-v4FESgraXE3a20G4',
    appId: '1:187217290981:android:bc1132d62a721177d9d60c',
    messagingSenderId: '187217290981',
    projectId: 'storage-3e09b',
    storageBucket: 'storage-3e09b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpa-IaoMY5bIIa3XBX6QObw7hJzK2GScQ',
    appId: '1:187217290981:ios:be111256c420c2f9d9d60c',
    messagingSenderId: '187217290981',
    projectId: 'storage-3e09b',
    storageBucket: 'storage-3e09b.appspot.com',
    iosClientId: '187217290981-tcbkc5sbqud9iegusmj85qolc80ec4bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpa-IaoMY5bIIa3XBX6QObw7hJzK2GScQ',
    appId: '1:187217290981:ios:be111256c420c2f9d9d60c',
    messagingSenderId: '187217290981',
    projectId: 'storage-3e09b',
    storageBucket: 'storage-3e09b.appspot.com',
    iosClientId: '187217290981-tcbkc5sbqud9iegusmj85qolc80ec4bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.storageTutorial',
  );
}
